--- Sentencias SQL para la creación del esquema de parranderos
--- Las tablas tienen prefijo A_ para facilitar su acceso desde SQL Developer

-- USO
-- Copie el contenido deseado de este archivo en una pestaña SQL de SQL Developer
-- Ejecútelo como un script - Utilice el botón correspondiente de la pestaña utilizada
    
-- Eliminar todas las tablas de la base de datos

DROP TABLE "ADMINISTRA";
DROP TABLE "ADMINISTRADOR" CASCADE CONSTRAINTS;
DROP TABLE "AFILIADO" CASCADE CONSTRAINTS;
DROP TABLE "AFILIACION" CASCADE CONSTRAINTS;
DROP TABLE "CAMPANA" CASCADE CONSTRAINTS;
DROP TABLE "CITA" CASCADE CONSTRAINTS;
DROP TABLE "CONTRATOS" CASCADE CONSTRAINTS;
DROP TABLE "DIRIGE" CASCADE CONSTRAINTS;
DROP TABLE "EPS" CASCADE CONSTRAINTS;
DROP TABLE "EXAMENDIAGNOSTICO" CASCADE CONSTRAINTS;
DROP TABLE "GERENTE" CASCADE CONSTRAINTS;
DROP TABLE "IPS" CASCADE CONSTRAINTS;
DROP TABLE "JOINMEDICOIPS" CASCADE CONSTRAINTS;
DROP TABLE "JOINRECEPCITA" CASCADE CONSTRAINTS;
DROP TABLE "MEDICO" CASCADE CONSTRAINTS;
DROP TABLE "ORDEN" CASCADE CONSTRAINTS;
DROP TABLE "ORGANIZA" CASCADE CONSTRAINTS;
DROP TABLE "ORGANIZADO" CASCADE CONSTRAINTS;
DROP TABLE "ORGANIZADOR" CASCADE CONSTRAINTS;
DROP TABLE "PROCEDIMIENTOESPECIALIZADO" CASCADE CONSTRAINTS;
DROP TABLE "RECEPCIONISTA" CASCADE CONSTRAINTS;
DROP TABLE "CITAS" CASCADE CONSTRAINTS;
DROP TABLE "RECIBEN" CASCADE CONSTRAINTS;
DROP TABLE "OFRECEN" CASCADE CONSTRAINTS;
DROP TABLE "ATENDIDAS" CASCADE CONSTRAINTS;
DROP TABLE "ROL" CASCADE CONSTRAINTS;
DROP TABLE "SERVICIO" CASCADE CONSTRAINTS;
DROP TABLE "TERAPIA" CASCADE CONSTRAINTS;
DROP TABLE "TIPO_SERVICIO" CASCADE CONSTRAINTS;
DROP TABLE "TRABAJAN" CASCADE CONSTRAINTS;
DROP TABLE "USUARIO" CASCADE CONSTRAINTS;

-- Eliminar el contenido de todas las tablas de la base de datos
-- El orden es importante. Por qué?

delete from GERENTE;
delete from EPS;
delete from IPS;
delete from CONTRATOS;
delete from DIRIGE;
delete from ADMINISTRA;
delete from AFILIACION;
delete from ADMINISTRADOR;
delete from MEDICO;
delete from SERVICIO;
delete from CITA;
delete from ORDEN;
delete from AFILIADO;
delete from RECEPCIONISTA;
delete from CITAS;
delete from RECIBEN;
delete from OFRECEN;
delete from ATENDIDAS;
delete from ORGANIZADO;
delete from CAMPANA;
delete from ORGANIZADOR;
delete from ORGANIZA;
delete from JOINRECEPCITA;
delete from JOINMEDICOIPS;
delete from EXAMENDIAGNOSTICO;
delete from TERAPIA;
delete from PROCEDIMIENTOESPECIALIZADO;
delete from TRABAJAN;
delete from ROL;
delete from TIPO_SERVICIO;

commit;